version: '3.8'

services:
  back_app:
    build:
      context: .
      dockerfile: dockerfile-Back
    ports:
      - "8085:8085"
    volumes:
      - ./backEnd:/app
  front_app:
    build:
      context: .
      dockerfile: dockerfile-Front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app



